services:
  server:
    extends:
      file: compose.base.yaml
      service: .redash
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "${REDASH_PORT:-5001}:5000"
      - "5678:5678"
    environment:
      PYTHONUNBUFFERED: 0
  scheduler:
    extends:
      file: compose.base.yaml
      service: .redash
    command: scheduler
    depends_on:
      - server
  worker:
    extends:
      file: compose.base.yaml
      service: .redash
    command: worker
    depends_on:
      - server
    environment:
      PYTHONUNBUFFERED: 0
  redis:
    image: redis:7-alpine
    restart: unless-stopped
  postgres:
    image: postgres:16-alpine
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    # The following turns the DB into less durable, but gains significant performance improvements for the tests run (x3
    # improvement on my personal machine). We should consider moving this into a dedicated Docker Compose configuration for
    # tests.
    command: postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  email:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: unless-stopped
  cypress:
    image: node:18-bookworm
    volumes:
      - $PWD:/app
    working_dir: /app
    environment:
      CYPRESS_baseUrl: http://server:5000
