[build]
  base    = "client"
  publish = "client/dist"
  # Netlify doesn't seem to install pnpm automatically
  # command = "cd ../ && npm i -g pnpm@10.30.3 && pnpm install --frozen-lockfile && cd viz-lib && pnpm run build:babel && cd .. && rm -r ./node_modules/@redash/viz && cp -r ./viz-lib/. ./node_modules/@redash/viz && pnpm run build && cd ./client"
  command = "cd ../ && npm i -g pnpm@10.30.3 && pnpm install --frozen-lockfile && pnpm run build && cd ./client"

[build.environment]
  NODE_VERSION = "24"
  CYPRESS_INSTALL_BINARY = "0"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "1"

[[redirects]]
  from = "/api/*"
  to = "http://preview-backend.redashapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/login"
  to = "http://preview-login.redashapp.com/login"
  status = 200

[[redirects]]
  from = "/logout"
  to = "http://preview-backend.redashapp.com/logout"
  status = 200

[[redirects]]
  from = "/status.json"
  to = "http://preview-backend.redashapp.com/status.json"
  status = 200

[[redirects]]
  from = "/static/server*"
  to = "http://preview-backend.redashapp.com/static/server:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
