apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redash.genericWorker.fullname" . }}
  labels:
    {{- include "redash.labels" . | nindent 4 }}
    app.kubernetes.io/component: genericworker
spec:
  replicas: {{ .Values.genericWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "redash.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: genericworker
  template:
    metadata:
      labels:
        {{- include "redash.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: genericworker
      {{- if .Values.genericWorker.podAnnotations }}
      annotations:
      {{ toYaml .Values.genericWorker.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "redash.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "redash.name" . }}-genericworker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", ". /config/dynamicenv.sh && /app/bin/docker-entrypoint worker"]
          volumeMounts:
            - name: config
              mountPath: /config
          env:
          {{- include "redash.env" . | nindent 12 }}
          {{- range $key, $value := .Values.genericWorker.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
          resources:
{{ toYaml .Values.genericWorker.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "redash.fullname" . }}
    {{- if .Values.genericWorker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.genericWorker.nodeSelector | indent 8 }}
    {{- end }}
    {{- with .Values.genericWorker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.genericWorker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
