version: 2.0

jobs:
  backend-lint:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: sudo pip install flake8
      - run: ./bin/flake8_tests.sh
  backend-unit-tests:
    environment:
      COMPOSE_FILE: .circleci/docker-compose.circle.yml
      COMPOSE_PROJECT_NAME: redash
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Images
          command: |
            set -x
            docker-compose build --build-arg skip_ds_deps=true --build-arg skip_frontend_build=true
            docker-compose up -d
            sleep 10
      - run:
          name: Create Test Database
          command: docker-compose run --rm postgres psql -h postgres -U postgres -c "create database tests;"
      - run:
          name: List Enabled Query Runners
          command: docker-compose run --rm redash manage ds list_types
      - run:
          name: Run Tests
          command: docker-compose run --name tests redash tests --junitxml=junit.xml --cov-report xml --cov=redash --cov-config .coveragerc tests/
      - run:
          name: Copy Test Results
          command: |
            mkdir -p /tmp/test-results/unit-tests
            docker cp tests:/app/coverage.xml ./coverage.xml
            docker cp tests:/app/junit.xml /tmp/test-results/unit-tests/results.xml
          when: always
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: coverage.xml
  frontend-lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: mkdir -p /tmp/test-results/eslint
      - run: npm ci
      - run: npm run lint:ci
      - store_test_results:
          path: /tmp/test-results
  frontend-unit-tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install python3-pip
      - run: sudo pip3 install -r requirements_bundles.txt
      - run: npm ci
      - run: npm run bundle
      - run:
          name: Run App Tests
          command: npm test
      - run:
          name: Run Visualizations Tests
          command: (cd viz-lib && npm test)
      - run: npm run lint
  build-docker-image:
    docker:
      - image: circleci/node:12
    steps:
      - setup_remote_docker
      - checkout
      - run: echo "export MOZILLA_VERSION=master" >> $BASH_ENV
      - run: sudo apt update
      - run: sudo apt install python3-pip
      - run: sudo pip3 install -r requirements_bundles.txt
      - run: .circleci/update_version
      - run: npm run bundle
      - run: .circleci/docker_build
  build-docker-image-tag:
    docker:
      - image: circleci/node:12
    steps:
      - setup_remote_docker
      - checkout
      - run: echo "export MOZILLA_VERSION=$CIRCLE_TAG" >> $BASH_ENV
      - run: sudo apt update
      - run: sudo apt install python3-pip
      - run: sudo pip3 install -r requirements_bundles.txt
      - run: .circleci/update_version
      - run: npm run bundle
      - run: .circleci/docker_build
      # Create alias from tag to "latest":
      - run: docker tag $DOCKERHUB_REPO:$CIRCLE_TAG $DOCKERHUB_REPO:latest
      - run: docker push $DOCKERHUB_REPO:latest
workflows:
  version: 2
  build:
    jobs:
      - backend-lint:
          filters:
            tags:
              only: /^m[0-9]+(\.[0-9]+)?$/
      - backend-unit-tests:
          filters:
            tags:
              only: /^m[0-9]+(\.[0-9]+)?$/
          requires:
            - backend-lint
      - frontend-lint:
          filters:
            tags:
              only: /^m[0-9]+(\.[0-9]+)?$/
      - frontend-unit-tests:
          filters:
            tags:
              only: /^m[0-9]+(\.[0-9]+)?$/
          requires:
            - backend-lint
            - frontend-lint
      - build-docker-image:
          requires:
            - backend-unit-tests
            - frontend-unit-tests
          filters:
            branches:
              only:
                - master
      - build-docker-image-tag:
          requires:
            - backend-unit-tests
            - frontend-unit-tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^m[0-9]+(\.[0-9]+)?$/
