version: '3'
services:
  server:
    build: ../
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_RATELIMIT_ENABLED: "false"
  scheduler:
    build: ../
    command: scheduler
    depends_on:
      - server
    environment:
      REDASH_REDIS_URL: "redis://redis:6379/0"
  worker:
    build: ../
    command: worker
    depends_on:
      - server
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  celery_worker:
    build: ../
    command: celery_worker
    depends_on:
      - server
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      QUEUES: "queries,scheduled_queries"
      WORKERS_COUNT: 2
  cypress:
    build:
      context: ../
      dockerfile: .circleci/Dockerfile.cypress
    depends_on:
      - server
      - celery_worker
      - worker
      - scheduler
    environment:
      CYPRESS_baseUrl: "http://server:5000"
      PERCY_TOKEN: ${PERCY_TOKEN}
      PERCY_BRANCH: ${CIRCLE_BRANCH}
      PERCY_COMMIT: ${CIRCLE_SHA1}
      PERCY_PULL_REQUEST: ${CIRCLE_PR_NUMBER}
      COMMIT_INFO_BRANCH: ${CIRCLE_BRANCH}
      COMMIT_INFO_AUTHOR: ${CIRCLE_USERNAME}
      COMMIT_INFO_SHA: ${CIRCLE_SHA1}
      COMMIT_INFO_REMOTE: ${CIRCLE_REPOSITORY_URL}
      CYPRESS_PROJECT_ID: ${CYPRESS_PROJECT_ID}
      CYPRESS_RECORD_KEY: ${CYPRESS_RECORD_KEY}
  redis:
    image: redis:3.0-alpine
    restart: unless-stopped
  postgres:
    image: postgres:9.5.6-alpine
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
