redash:
  image: redash/redash
  ports:
    - "5000:5000"
  links:
    - redis
    - postgres
  environment:
    REDASH_LOG_LEVEL: INFO
    REDASH_REDIS_URL: redis://redis:6379/0
    REDASH_DATABASE_URL: postgresql://postgres@postgres/postgres
    REDASH_COOKIE_SECRET: veryverysecret
redis:
  image: redis:2.8
postgres:
  image: postgres:9.3
  volumes:
   - /opt/redash-docker/postgres-data:/var/lib/postgresql/data
nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - "/opt/redash-docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
  links:
    - redash
